[package]
name = "ac_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.6"
goblin = "0.9.3"
libc = "0.2.170"
log = "0.4.26"

[build-dependencies]
bindgen = "0.71.1"
pkg-config = "0.3.32"
